language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
# command to install dependencies
# install: 'pip install -r requirements.txt'

install:
   - pip install flake8
   - pip install codecov

before_script:
   flake8 .

# command to run tests
script:
  py.test --cov --cov-config .coveragerc

after_success:
   - codecov